export const config={api:{bodyParser:{sizeLimit:'10mb'}},maxDuration:60};
function getKey(){return process.env.OPENAI_API_KEY||process.env['CLÉ_API_OPENAI']||process.env.CLE_API_OPENAI;}
function parseDataUrl(dataUrl){const m=/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/s.exec(dataUrl||'');if(!m)throw new Error('Image invalide');return{type:m[1],buffer:Buffer.from(m[2],'base64')};}
function extFor(type){return type.includes('png')?'png':type.includes('webp')?'webp':'jpg';}
const carSteps={2:'detach ALL FOUR wheels only. Each wheel must visibly leave its hub and float outward near that same hub. Keep the body otherwise fully assembled',3:'detach BOTH doors only. The left and right doors must visibly leave the body and float outward beside their original door openings. Wheels remain exactly frozen where they already are',4:'detach ONLY the hood. It must visibly leave the body and float above and slightly forward of the engine bay. Wheels and doors stay frozen exactly where they were',5:'detach ONLY the windshield / windscreen assembly. It must visibly leave the cabin and float above it. All prior detached parts stay frozen',6:'detach ONLY the front bumper assembly. It must visibly move forward away from the nose. All prior detached parts stay frozen',7:'detach ONLY the rear bumper assembly. It must visibly move backward away from the tail. All prior detached parts stay frozen',8:'detach ONLY the major front fenders, rocker panels and large side body panels. Move them outward into clean technical floating positions. All prior detached parts stay frozen',9:'detach ONLY the engine and transmission together as ONE major powertrain block if visible and mechanically appropriate. Keep the chassis/cell central and keep EVERY previously detached part visible and frozen'};
const motoSteps={2:'detach BOTH wheels only and move them outward to fixed floating positions',3:'detach ONLY the seat and major rear accessories to fixed floating positions',4:'detach ONLY the tank and major body covers to fixed floating positions',5:'detach ONLY the headlight and mirrors to fixed floating positions',6:'detach ONLY the fork and major suspension assemblies to fixed floating positions',7:'detach ONLY the exhaust assemblies to fixed floating positions',8:'detach ONLY the engine as one complete block to a fixed floating position',9:'leave the frame/chassis central while keeping every previously detached part visible at its exact previous position'};
function stepText(type,stage){if(type==='car')return carSteps[stage]||carSteps[9];if(type==='motorcycle')return motoSteps[stage]||motoSteps[9];return `detach ONLY one new large meaningful assembly appropriate for stage ${stage}, placing it in a clearly visible fixed floating exploded-view position`;}
function cleanType(v){const s=String(v||'object').toLowerCase();if(s.includes('moto'))return'motorcycle';if(s.includes('voiture')||s.includes('car'))return'car';if(s.includes('outil')||s.includes('tool'))return'tool';if(s.includes('machine'))return'industrial machine';return'object';}
function cleanSize(v){return ['1536x1024','1024x1536','1024x1024'].includes(v)?v:'1536x1024';}
function promptFor(type,stage){return `This image is STATE ${stage-1} of a cumulative technical ExplodeView. Create STATE ${stage} by editing this exact image, not by redesigning it.

GEOMETRY LOCK — ABSOLUTELY CRITICAL:
- Preserve the exact vehicle/object proportions from the input image. NEVER squash, stretch, widen, narrow, shorten or vertically compress it.
- Preserve wheelbase, track width, body height, cabin height, hood length and perspective.
- Preserve the exact camera viewpoint, horizon, crop logic and overall object scale.
- The central vehicle/object must occupy approximately the same visual dimensions as in the input.

STATE-MACHINE RULES:
1. Every part already detached in the input image is LOCKED. Keep each one visible at exactly the same position, orientation, size and side.
2. Never make a detached part disappear, move, reattach, duplicate, swap sides or change shape.
3. This state MUST make one NEW mechanical change that is immediately obvious. Do not return an almost identical image.
4. Change ONLY this one new group: ${stepText(type,stage)}.
5. Everything else must remain visually unchanged in placement, geometry, color and identity as much as possible.
6. Detached parts FLOAT around the object in elegant modern technical positions; never place them on the floor.
7. No screws, bolts, nuts, clips, washers, loose cables, tiny brackets or micro-parts. Never disassemble the engine internally.
8. Modern premium technical exploded-view aesthetic, clean and suitable for 9-view lenticular animation.

Output one single full-frame image only. No contact sheet, no text, no labels, no borders, no numbers.`;}
async function callOpenAI(key,imageDataUrl,type,stage,size){const src=parseDataUrl(imageDataUrl),form=new FormData();form.append('model','gpt-image-2');form.append('image[]',new Blob([src.buffer],{type:src.type}),`state-${stage-1}.${extFor(src.type)}`);form.append('prompt',promptFor(type,stage));form.append('size',cleanSize(size));form.append('quality','low');form.append('output_format','jpeg');form.append('output_compression','88');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),55000);try{const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form,signal:controller.signal});const text=await r.text();let j;try{j=JSON.parse(text)}catch{j=null}if(!r.ok)throw new Error(`OpenAI ${r.status}: ${j?.error?.message||text.slice(0,500)||'erreur inconnue'}`);const b64=j?.data?.[0]?.b64_json;if(!b64)throw new Error('OpenAI n’a retourné aucune image.');return b64;}catch(e){if(e?.name==='AbortError')throw new Error(`Vue ${stage}: délai dépassé. Relance la génération.`);throw e;}finally{clearTimeout(timeout);}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const key=getKey();if(!key)return res.status(500).json({error:'OPENAI_API_KEY absente sur Vercel'});try{const {imageDataUrl,objectType='object',stage,imageSize='1536x1024'}=req.body||{};const n=Math.max(2,Math.min(9,Number(stage)||2));const size=cleanSize(imageSize);const b64=await callOpenAI(key,imageDataUrl,cleanType(objectType),n,size);res.setHeader('Cache-Control','no-store');return res.status(200).json({imageDataUrl:'data:image/jpeg;base64,'+b64,stage:n,imageSize:size,mode:'sequential-cumulative-geometry-lock'});}catch(e){console.error('[explodeview-step]',e);return res.status(500).json({error:e?.message||'Erreur ExplodeView'});}}
