export const config={api:{bodyParser:{sizeLimit:'10mb'}},maxDuration:60};
function getKey(){return process.env.OPENAI_API_KEY||process.env['CLÉ_API_OPENAI']||process.env.CLE_API_OPENAI;}
function parseDataUrl(dataUrl){const m=/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/s.exec(dataUrl||'');if(!m)throw new Error('Image invalide');return{type:m[1],buffer:Buffer.from(m[2],'base64')};}
function extFor(type){return type.includes('png')?'png':type.includes('webp')?'webp':'jpg';}
const carSteps={2:'detach ONLY the four wheels and move them outward to clean floating exploded-view positions beside their original hubs',3:'detach ONLY the doors and move them outward to fixed floating positions',4:'detach ONLY the hood and move it upward/forward to a fixed floating position',5:'detach ONLY the windshield and move it upward to a fixed floating position',6:'detach ONLY the front bumper and move it forward to a fixed floating position',7:'detach ONLY the rear bumper and move it backward to a fixed floating position',8:'detach ONLY the major fenders, rocker panels and side body panels and move them outward to clean fixed floating positions',9:'detach ONLY the engine/transmission as one major block if mechanically appropriate, leaving the chassis/cell central'};
const motoSteps={2:'detach ONLY the wheels and move them outward to fixed floating positions',3:'detach ONLY the seat and major rear accessories to fixed floating positions',4:'detach ONLY the tank and major body covers to fixed floating positions',5:'detach ONLY the headlight and mirrors to fixed floating positions',6:'detach ONLY the fork and major suspension assemblies to fixed floating positions',7:'detach ONLY the exhaust assemblies to fixed floating positions',8:'detach ONLY the engine as one complete block to a fixed floating position',9:'leave the frame/chassis central while keeping every previously detached part visible at its exact previous position'};
function stepText(type,stage){if(type==='car')return carSteps[stage]||carSteps[9];if(type==='motorcycle')return motoSteps[stage]||motoSteps[9];return `detach ONLY one new large meaningful assembly appropriate for stage ${stage}, placing it in a clean fixed floating exploded-view position`;}
function cleanType(v){const s=String(v||'object').toLowerCase();if(s.includes('moto'))return'motorcycle';if(s.includes('voiture')||s.includes('car'))return'car';if(s.includes('outil')||s.includes('tool'))return'tool';if(s.includes('machine'))return'industrial machine';return'object';}
function promptFor(type,stage){return `This image is STATE ${stage-1} of a cumulative technical ExplodeView. Create STATE ${stage} by editing this exact image, not by redesigning it. Preserve the same object identity, camera, crop, lighting, background, scale and composition.\n\nCRITICAL STATE-MACHINE RULES:\n1. Every part already detached in the input image is LOCKED. Keep each one visible at exactly the same position, orientation, size and side.\n2. Never make a detached part disappear, move, reattach, duplicate, swap sides or change shape.\n3. Change ONLY this one new group: ${stepText(type,stage)}.\n4. Everything else must remain pixel-consistent in placement as much as possible.\n5. Detached parts FLOAT around the object in elegant technical positions; never place them on the floor.\n6. No screws, bolts, nuts, clips, washers, loose cables, tiny brackets or micro-parts. Never disassemble the engine internally.\n7. Modern premium technical exploded-view aesthetic, clean and suitable for 9-view lenticular animation.\n\nOutput one single full-frame image only. No contact sheet, no text, no labels, no borders, no numbers.`;}
async function callOpenAI(key,imageDataUrl,type,stage){const src=parseDataUrl(imageDataUrl),form=new FormData();form.append('model','gpt-image-2');form.append('image[]',new Blob([src.buffer],{type:src.type}),`state-${stage-1}.${extFor(src.type)}`);form.append('prompt',promptFor(type,stage));form.append('size','1024x1024');form.append('quality','low');form.append('output_format','jpeg');form.append('output_compression','88');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),55000);try{const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form,signal:controller.signal});const text=await r.text();let j;try{j=JSON.parse(text)}catch{j=null}if(!r.ok)throw new Error(`OpenAI ${r.status}: ${j?.error?.message||text.slice(0,500)||'erreur inconnue'}`);const b64=j?.data?.[0]?.b64_json;if(!b64)throw new Error('OpenAI n’a retourné aucune image.');return b64;}catch(e){if(e?.name==='AbortError')throw new Error(`Vue ${stage}: délai dépassé. Relance la génération.`);throw e;}finally{clearTimeout(timeout);}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const key=getKey();if(!key)return res.status(500).json({error:'OPENAI_API_KEY absente sur Vercel'});try{const {imageDataUrl,objectType='object',stage}=req.body||{};const n=Math.max(2,Math.min(9,Number(stage)||2));const b64=await callOpenAI(key,imageDataUrl,cleanType(objectType),n);res.setHeader('Cache-Control','no-store');return res.status(200).json({imageDataUrl:'data:image/jpeg;base64,'+b64,stage:n,mode:'sequential-cumulative'});}catch(e){console.error('[explodeview-step]',e);return res.status(500).json({error:e?.message||'Erreur ExplodeView'});}}
